### ISSUE TITLE
tn3399编译主线UBOOT DDR无法过检测问题

### ISSUE THREAD

**Issue by 287662354** [retro98boy/linux-tn3399-v3#10]
我自己按照evb RK3399板子的默认配置   默认的设备树 (evb-rk3399)编译后  DDR检测不过 ,使用您的补丁后没有问题 ,请问一下是哪个设置有问题吗`
U-Boot TPL 2024.01-rc5-00011-g0a0ceea226 (Dec 28 2023 - 12:10:00)
sdram_init: LPDDR3 - 800MHz failed!
rk3399_dmc_init DRAM init failed -22
Missing DTB
`
按照您补丁的配置设置了以后依然是这样子

**Comment by retro98boy** [comment]
> 我自己按照evb RK3399板子的默认配置 默认的设备树 (evb-rk3399)编译后 DDR检测不过 ,使用您的补丁后没有问题 ,请问一下是哪个设置有问题吗`U-Boot TPL 2024.01-rc5-00011-g0a0ceea226 (Dec 28 2023 - 12:10:00) sdram_init: LPDDR3 - 800MHz failed! rk3399_dmc_init DRAM init failed -22 Missing DTB` 按照您补丁的配置设置了以后依然是这样子

这个板子是dd3的内存，使用evb rk3399的配置，会尝试使用lpddr3的参数初始化内存，当然会失败

使用什么内存，多少频率在设备树中指定，看这里

https://github.com/retro98boy/linux-tn3399-v3/blob/64786f5cfd65dc5b068dc76515ccd73603e40e3d/u-boot/u-boot-2023.07.02-add-tn3399-v3.patch#L25C20-L25C20

**Comment by 287662354** [comment]
> > 我自己按照evb RK3399板子的默认配置 默认的设备树 (evb-rk3399)编译后 DDR检测不过 ,使用您的补丁后没有问题 ,请问一下是哪个设置有问题吗`U-Boot TPL 2024.01-rc5-00011-g0a0ceea226 (Dec 28 2023 - 12:10:00) sdram_init: LPDDR3 - 800MHz failed! rk3399_dmc_init DRAM init failed -22 Missing DTB` 按照您补丁的配置设置了以后依然是这样子
> 
> 这个板子是dd3的内存，使用evb rk3399的配置，会尝试使用lpddr3的参数初始化内存，当然会失败
> 
> 使用什么内存，多少频率在设备树中指定，看这里
> 
> https://github.com/retro98boy/linux-tn3399-v3/blob/64786f5cfd65dc5b068dc76515ccd73603e40e3d/u-boot/u-boot-2023.07.02-add-tn3399-v3.patch#L25C20-L25C20
感谢您的回复,目前已经找到问题来源
