### ISSUE TITLE
硬件支持情况

### ISSUE THREAD

**Issue by GWan1234** [retro98boy/linux-tn3399-v3#3]
感谢大佬的整理与维护，请问这个arm能够正常使用板子上面的云盘接口么？就是未焊接的那个耳机接口，我试了几个版本都不行。

**Comment by retro98boy** [comment]
这个板子有一个ALC5640的codec，一个音频输出到耳机jack，一个输出到板子上的运放。但是我没有调通这颗codec，所以声音只能走HDMI一条路了。
还有板子上的edp，lvds，camera我是没调的，因为用不到。

**Comment by retro98boy** [comment]
> 感谢大佬的整理与维护，请问这个arm能够正常使用板子上面的云盘接口么？就是未焊接的那个耳机接口，我试了几个版本都不行。

这个板子有一个ALC5640的codec，一个音频输出到耳机jack，一个输出到板子上的运放。但是我没有调通这颗codec，所以声音只能走HDMI一条路了。
还有板子上的edp，lvds，camera我是没调的，因为用不到。

**Comment by gulang123** [comment]
> > 感谢大佬的整理与维护，请问这个arm能够正常使用板子上面的云盘接口么？就是未焊接的那个耳机接口，我试了几个版本都不行。
> 
> 这个板子有一个ALC5640的codec，一个音频输出到耳机jack，一个输出到板子上的运放。但是我没有调通这颗codec，所以声音只能走HDMI一条路了。 还有板子上的edp，lvds，camera我是没调的，因为用不到。

大佬，能不能简单介绍下，这个板子怎么调试LVDS接口那块，我买了个10寸显示屏，想着搭配板子做个平板或者啥东西的。谢谢了。
