### ISSUE TITLE
屏蔽uas驱动

### ISSUE THREAD

**Issue by artosynTec** [retro98boy/linux-tn3399-v3#8]
hello，我刷了这个系统之后，在usb3.0上挂了一块硬盘，但是在大数据量写入的时候，会掉盘，看了dmesg，应该是uas的驱动导致的，我尝试了在blacklist.conf里面添加了uas，但是系统启动的时候，还是把uas驱动加载上了，这个uas驱动应该怎么禁用😄

**Comment by retro98boy** [comment]
> hello，我刷了这个系统之后，在usb3.0上挂了一块硬盘，但是在大数据量写入的时候，会掉盘，看了dmesg，应该是uas的驱动导致的，我尝试了在blacklist.conf里面添加了uas，但是系统启动的时候，还是把uas驱动加载上了，这个uas驱动应该怎么禁用😄

uas驱动编译进内核了，而不是已模块形式存在，所以通过modprobe黑名单是不行的

可以给usb-storage模块指定参数屏蔽特定u盘的uas，当然这个模块也编译进内核了，通过modprobe的option选项是不行的，需要通过内核参数来设置

比如manjaro通过extlinux来引导内核，编辑/boot/extlinux/extlinux.conf，有一行append就是给内核添加参数，在尾部加上usb-storage.quirks=1f75:0903:u即可，其中1f75:0903通过lsusb得出，是u盘的vid pid

**Comment by artosynTec** [comment]
可以了，感谢老哥
