### ISSUE TITLE
存在异常断网情况，5Gwifi开机一会后断线

### ISSUE THREAD

**Issue by wangfreexx** [retro98boy/linux-tn3399-v3#9]
首先感谢大佬的编译，固件很好用，但是存在一个我百思不得其解的问题，连接5Gwifi时，开机到开机后3分钟，5Gwifi连接没有问题，nmtui可以搜到5G，可以上传下载ssh，但是3分钟左右后5Gwifi断掉，再也搜不到，只能2.4G。
同时存在以下问题：5Gwifi 偶尔重启后可以一直正常连接，不会出问题，重启失效
已经试过频段问题，没有解决，怀疑NetworkManager 冲突或者驱动问题

**Comment by retro98boy** [comment]
> 首先感谢大佬的编译，固件很好用，但是存在一个我百思不得其解的问题，连接5Gwifi时，开机到开机后3分钟，5Gwifi连接没有问题，nmtui可以搜到5G，可以上传下载ssh，但是3分钟左右后5Gwifi断掉，再也搜不到，只能2.4G。 同时存在以下问题：5Gwifi 偶尔重启后可以一直正常连接，不会出问题，重启失效 已经试过频段问题，没有解决，怀疑NetworkManager 冲突或者驱动问题

哪个固件，我抽空看看

**Comment by wangfreexx** [comment]
armbian最新的2023.10.2号的固件

**Comment by retro98boy** [comment]
> 首先感谢大佬的编译，固件很好用，但是存在一个我百思不得其解的问题，连接5Gwifi时，开机到开机后3分钟，5Gwifi连接没有问题，nmtui可以搜到5G，可以上传下载ssh，但是3分钟左右后5Gwifi断掉，再也搜不到，只能2.4G。 同时存在以下问题：5Gwifi 偶尔重启后可以一直正常连接，不会出问题，重启失效 已经试过频段问题，没有解决，怀疑NetworkManager 冲突或者驱动问题

我刷写了固件，连接5G WiFi，通过ssh连接上板子，静置一段时间后连接没有断开，然后使用使用iperf3和局域网里的设备测速，长时间下来也没有断开，速度稳定在10MB/s

通过apt upgrade所有软件到最新，重启后重新进行上述测试，也没断过。我的板子接了ipex 一代天线

针对你的现象：

要不加个天线？没有天线的话，把板子挨着到路由器/手机热点来测试稳定性

nmtui界面不显示WiFi后，执行：

```
sudo nmcli device wifi rescan
sudo nmcli device wifi list
```

看看是否能搜到WiFI信号

**Comment by wangfreexx** [comment]
![image](https://github.com/retro98boy/linux-tn3399-v3/assets/23137882/260c915b-566e-4512-bac2-dfd9a4432dae)
我加了天线，和路由器只有1米距离，可能是因为我乱动了什么设置原因，现在2.4g也·能用，再次感谢，请教下如果新固件的话怎么无损升级？

**Comment by retro98boy** [comment]
> ![image](https://private-user-images.githubusercontent.com/23137882/287445668-260c915b-566e-4512-bac2-dfd9a4432dae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTgzMjEsIm5iZiI6MTcwMTUxODAyMSwicGF0aCI6Ii8yMzEzNzg4Mi8yODc0NDU2NjgtMjYwYzkxNWItNTY2ZS00NTEyLWJhYzItZGZkOWE0NDMyZGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExNTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZDg1NTYwYjlkNzMxYzAyZDZjYTJlYzhmNjQ2ODZkNDBkMTZiYjM4YjkzZmJmZjI0YTEzOTAwZWYwMjk3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I7303cJduyKhpnyep62DX3P3w3BVPz5_UQl4zW4E6c8) 我加了天线，和路由器只有1米距离，可能是因为我乱动了什么设置原因，现在2.4g也·能用，再次感谢，请教下如果新固件的话怎么无损升级？


新的固件对比旧的固件：

- 更新了软件包

- 从自编译内核切换到官方内核

- 升级了dtb，主要更改了板子的名字，所以ap6255固件名字也改了

手动升级：

- 替换/boot下面的dtb为仓库最新版本

- 自行将仓库中ap6255固件放到/lib/firmware/brcm下面

- apt安装官方的6.6.2内核，之前6.1.50内核HDMI失效才自编译内核

```
apt install linux-image-edge-rockchip64 linux-dtb-edge-rockchip64 linux-headers-edge-rockchip64
```

升级完成后`ls -Alh /boot`确定下一些软链接是否指向新内核，例如Image指向6.6.2内核而不是6.5.5。确认完毕就可以重启了
